on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          package-name: ${{ github.event.repository.name }}
  build:
    runs-on: ubuntu-latest
    needs: release-please
    strategy:
      matrix:
        goos:
          - linux
          - darwin
          - windows
        goarch:
          - amd64
          - arm64
    env:
      output_name: ${{ github.event.repository.name }}_${{ needs.release-please.outputs.tag_name }}_${{ matrix.goos }}_${{ matrix.goarch }}
      tag_name: ${{ needs.release-please.outputs.tag_name }}
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: go mod tidy
      - if: ${{ matrix.goos == 'windows'}}
        run: go build -o build/${{ env.output_name }}.exe -ldflags '-s -w -X github.com/Falklian/cloudflare-ddns/cmd.version=${{ env.tag_name }}'
      - if: ${{ matrix.goos != 'windows' }}
        run: go build -o build/${{ env.output_name }} -ldflags '-s -w -X github.com/Falklian/cloudflare-ddns/cmd.version=${{ env.tag_name }}'
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: build/${{ env.output_name }}*
          tag: ${{ env.tag_name }}
